---
deployment:
  tasks:
    # Install dependencies
    - export DEPLOYPATH=/home/foilexyo/public_html
    - /usr/bin/npm install --prefix $HOME/repositories/foil-industries

    # Build the Astro site
    - /usr/bin/npm run build --prefix $HOME/repositories/foil-industries

    # Copy built files to public directory
    - /bin/cp -R $HOME/repositories/foil-industries/dist/* $DEPLOYPATH/
